### ISSUE TITLE
v1.0.2 List All Available Titles results in full download

### ISSUE THREAD

**Issue by mj23au** [billybanana80/DevineGUI#1]
I noticed in 1.0.2 "List All Available Titles" is now actually downloading everything and not actually listing the titles

![image](https://github.com/billybanana80/DevineGUI/assets/92862622/e590762f-155c-4d99-994a-39118a214d63)

**Comment by billybanana80** [comment]
I've pushed a new release v1.0.3 to fix this issue. Thanks for reporting it.
